# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b275b1776003ea12311cb556d979d7a874487f9fbf9e948cce78ea3ba6c5d01cc3faa00dbda4cb849480e508a64e4c4485fe928b3e471b795d470beb40ea7f

test:
  secret_key_base: 85367e4d1197ebbe39c486f05ed7829d6a4da07dd49e1a6408b348949a638df3edd60ea7cafcb8076001a3b32e5138501905f6b84ffe412273bdf4316cb20d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
